# Uncomment the next line to define a global platform for your project
#platform :ios, '11.0'

target 'EnricTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EnricTest
  pod 'Toast-Swift', '~> 3.0.1'

  target 'EnricTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
